spring.datasource.url=jdbc:postgresql://localhost:5432/chatgpt_bookmarks
spring.datasource.username=chatgpt_bookmark
spring.datasource.password=chatgpt_bookmark
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
server.port=8080
app.frontend-base-url=http://localhost:3000
app.auth.jwt-secret=${APP_AUTH_JWT_SECRET:change-me-in-production-change-me-in-production}
app.auth.cookie-name=auth_token
app.auth.cookie-secure=false
app.auth.cookie-same-site=Lax
app.auth.token-expiry-hours=24
app.auth.remember-me-token-expiry-days=7

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chatgptbookmark@gmail.com
spring.mail.password=ruhpltvoqtalktod
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=chatgptbookmark@gmail.com
app.email-verification.cleanup-cron=0 0 * * * *
