spring.datasource.url=jdbc:postgresql://localhost:5432/chatgpt_bookmarks
spring.datasource.username=chatgpt_bookmark
spring.datasource.password=chatgpt_bookmark
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
server.port=8080
